source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'typhoeus'
gem 'hashie'
gem 'rake'
gem 'ruby-debug19'
gem 'cheat'
gem 'mysql2', '0.2.6'
gem 'wirble'
gem 'hirb'
gem 'thin'
gem 'awesome_print'
gem 'what_methods'
gem 'map_by_method'
gem 'will_paginate'
gem 'resque'
gem 'whenever'
gem 'eventmachine'
gem 'em-http-request'
gem 'haml'
gem 'ruby-prof'
gem 'metrical'
gem 'crewait', :git => 'https://github.com/blake41/crewait'
gem 'looksee'


group :test, :development do
  gem 'mocha'
  gem 'rspec-rails'
  gem 'rspec'
  gem 'factory_girl'
  gem 'autotest'
  gem 'fakeweb'
end
